apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
   name: {{ .Values.istio.gateway.name }}
spec:
  selector:
    istio: {{ .Values.istio.name }}
  servers:
  - port:
      number: {{ .Values.istio.gateway.port }}
      name: http
      protocol: HTTP
    tls:
      mode: {{ .Values.istio.gateway.tlsMode }}
      credentialName: {{ .Values.keyVault.tlsCertificateName }}
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo-vs-external
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.istio.gateway.name }}
  http:
  - match:
    - uri:
        exact: /healthz
    route:
    - destination:
        host: healthz
        port:
          number: 8080